### ISSUE TITLE
Dynamic message support

### ISSUE THREAD

**Issue by ryanmr** [MaxLi1994/redux-validator#5]
Hi. I have been using your library in a project and it has been useful and has worked great.

Recently, I ran into a scenario using `react-i18n` for internationalization support that would be solved by adding dynamic message support, I think.

Example
```
import i18n from '@/i18n'

const dateTimeValidator = [
  {
    func: (v, s, p) => Number.isInteger(v),
    // this value will only get evaluated and then stored once
    // when the validator is created the first time
    // and on subsequent runs, even if the language is changed
    // in i18n, it will never be reflected here
    msg: i18n.t('common:validation.dateTimeNumber')
  },
]

// redux action creator
export function addPlacement(
  message,
  placementId = uuidv4()
) {
  const action = {
    type: R_ADD_PLACEMENT,
    payload: {
      message,
      placementId
    },
    meta: {
      // v: value to validate, s: state, p: action payload
      validator: {
        deliveryDate: dateTimeValidator
      }
    }
  }
  return action
}
```

I think the ideal way to add dynamic message support would be to allow a function to return a string, similar to how `func` returns a `boolean`.

In [this code](https://github.com/MaxLi1994/redux-validator/blob/master/src/validator.babel#L35), you could add:

```
if(!flag) {
    errorParam = key;
    errorId = id;
    errorMsg = (typeof msg === 'function' ? msg(param, store.getState(), action.payload) : msg) || '';
}
```

The message function would take the same arguments as `func` to keep the interface the same but provide a runtime based value and allow for more powerful error messages, and would fallback to string format to preserve backwards compatibility.

Thank you for the consideration.

**Comment by ryanmr** [comment]
Hi, I wanted to follow up.

A way to make this closer to what I needed was to make the `dateTimeValidator` a function rather than a fixed array of rules.

```
const dateTimeValidator = () => ([
  {
    func: (v, s, p) => Number.isInteger(v),
    // this will be re-evaluated each time, and should react to language state changes on next run
    msg: i18n.t('common:validation.dateTimeNumber')
  }
])
```

Then it can be referenced in the meta validator section as `dateTimeValidator()`. The PR I submitted will still expand flexibility, but this covers my use case well enough.

**Comment by ymaxli** [comment]
Hi, thank you for your PR. I'm sorry for this delayed reply. I'm on vacation now and I was not checking email regularly the last few days😂 I'll check this out a couple hours later. Thanks again for your contribution and Happy New Year!

**Comment by ryanmr** [comment]
Hey, no worries -- no hurry, enjoy your vacation! Happy new year!

**Comment by ymaxli** [comment]
Your modification definitely adds flexibility to the error msg functionality. Although creating a new validator every time to generate a new error message may work for your use case, it seems a hack to me. The more reasonable way of solving this is making the msg parameter a dynamic function. Your PR looks fine to me.
However, I don't have a laptop in hand now so I can't merge the pull request let alone update the NPM package. I'll do these things when I get home in a few days. Before then, you may have to hack your local version.😂
Thanks again!

**Comment by ryanmr** [comment]
Thanks for taking the time to look it over. For now, work around is working just fine. No hurries, thanks again!

**Comment by ymaxli** [comment]
I've merged your PR and updated the NPM package! Thanks again!

**Comment by ryanmr** [comment]
Awesome! Thank you for the work too!
